Add a tool list in readme file
Elektrobit/nautilos-repo-setup pull request #1
Opened 2022-12-16 14:45 UTC by JiyangLiuG

@schaefi You could decline this if you think it is not necessary. The code is very well self explained.

2022-12-16 15:27 UTC, isbm requested changes

2022-12-16 15:27 UTC, isbm commented on README.rst
> +Tool list:
List of tools.

2022-12-16 15:27 UTC, isbm commented on README.rst
> +  Print available release dates
- `ebcl-releases`
  Prints available release dates
- `ebcl-repo-setup`
  Setup tool for package repositories and cache updates
- `ebcl-sync`
  Package repository syncer
- `ebcl-ui`
  SDK setup tool

2023-01-20 17:41 UTC, isbm commented on README.rst
> +  Print available release dates
I believe the syntax is:

```markdown
- `fixed list item`
  Explanation comment

- `another fixed list item`
  Another explanation comment
```

So it is rendered then:

> - `fixed list item`
  Explanation comment
>
> - `another fixed list item`
  Another explanation comment

2023-01-20 17:45 UTC, isbm requested changes
Commented

2023-06-23 12:55 UTC, JiyangLiuG commented on README.rst
> +  Print available release dates
Hi @isbm , sorry, i missed this comment. 
The syntax you used is rendered as.

```
fixed list item Explanation comment
another fixed list item Another explanation comment
```

And i checked https://sublime-and-sphinx-guide.readthedocs.io/en/latest/, 
Lists shall be started with '#' or '*', but not '-'.

Why you use '' about the list item, you would like to achieve which effect? Interpreted text? https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#toc-entry-49

2023-06-23 12:56 UTC, JiyangLiuG commented
> Commented

replied above.

2023-08-03 05:54 UTC, JiyangLiuG commented
open for too long. Will be done in other pull request together.

2023-08-03 05:54 UTC, closed without merging